export const LEDGER_ERROR_CODES = {
  LEDGER_ACCOUNT_NOT_FOUND: 'LEDGER_ACCOUNT_NOT_FOUND',
  LEDGER_ACCOUNT_ARCHIVED: 'LEDGER_ACCOUNT_ARCHIVED',
  LEDGER_ACCOUNT_CODE_CONFLICT: 'LEDGER_ACCOUNT_CODE_CONFLICT',
  LEDGER_ACCOUNT_CODE_INVALID: 'LEDGER_ACCOUNT_CODE_INVALID',
  LEDGER_TRANSACTION_UNBALANCED: 'LEDGER_TRANSACTION_UNBALANCED',
  LEDGER_TRANSACTION_TOO_FEW_ENTRIES: 'LEDGER_TRANSACTION_TOO_FEW_ENTRIES',
  LEDGER_TRANSACTION_NOT_FOUND: 'LEDGER_TRANSACTION_NOT_FOUND',
  LEDGER_CURRENCY_MISMATCH: 'LEDGER_CURRENCY_MISMATCH',
  LEDGER_CURRENCY_INVALID: 'LEDGER_CURRENCY_INVALID',
  LEDGER_CROSS_TENANT_ACCOUNT: 'LEDGER_CROSS_TENANT_ACCOUNT',
  LEDGER_INVALID_AMOUNT: 'LEDGER_INVALID_AMOUNT',
  LEDGER_INVALID_SIDE: 'LEDGER_INVALID_SIDE',
  LEDGER_INVALID_ACCOUNT_TYPE: 'LEDGER_INVALID_ACCOUNT_TYPE',
  LEDGER_INVALID_TRANSACTION_TYPE: 'LEDGER_INVALID_TRANSACTION_TYPE',
  LEDGER_INVALID_REFERENCE: 'LEDGER_INVALID_REFERENCE',
  LEDGER_INVALID_REVERSAL: 'LEDGER_INVALID_REVERSAL',
  LEDGER_DESCRIPTION_INVALID: 'LEDGER_DESCRIPTION_INVALID',
} as const;

export type LedgerErrorCode = (typeof LEDGER_ERROR_CODES)[keyof typeof LEDGER_ERROR_CODES];

export class LedgerError extends Error {
  readonly code: LedgerErrorCode;

  constructor(code: LedgerErrorCode, message: string) {
    super(message);
    this.name = 'LedgerError';
    this.code = code;
  }
}

export function isLedgerError(error: unknown): error is LedgerError {
  return error instanceof LedgerError;
}
